Clash Map for predicting active conformations.
primaryodors/primarydock pull request #194
Opened 2023-01-20 18:34 UTC by ssepeq

There's a lot in this PR, but the main things are:

- Clash map generation that can be used to estimate the binding pocket changes for OR activation;
- Improved Best-Binding algorithm that groups ligand atoms and protein residues into "gloms", and aligns them;
- Infrastructure for active-first predictions;
- Misc fixes.

2023-01-20 18:34 UTC, ssepeq commented
![ADORA2_cmp](https://user-images.githubusercontent.com/66374250/213779079-6db9a509-97b9-42eb-a64e-213ff6485f4d.png)

2023-01-21 00:57 UTC, ssepeq commented
🟨🟩🟩

2023-01-21 04:47 UTC, primaryodors commented
While the clash map is a really awesome development, and there is a lot in this PR worth saving, it would probably be best to review this as just docking quality improvements and move on to #195.

2023-01-21 17:03 UTC, primaryodors requested changes

2023-01-21 17:03 UTC, primaryodors commented on src/primarydock.cpp
> +                bool toosame = false;
Should rename this to `too_similar` everywhere it occurs.

2023-01-21 17:05 UTC, primaryodors approved these changes

2023-01-21 21:02 UTC, primaryodors commented
🟩🟩🟩

2023-01-21 21:02 UTC, merged