Incremental rock. #200
primaryodors/primarydock pull request #214
Opened 2023-03-17 03:14 UTC by ssepeq

Mixed results with SCFAs in OR51E2. Predicts diacetyl correctly as non-agonist. Ionones and δ-decalactone are failing to make a complete dock.

2023-03-20 04:08 UTC, ssepeq commented
🟩🟩🟩

2023-03-21 04:46 UTC, ssepeq commented
Waiting on the server to process all of the empirical ligands for OR51E1 and 51E2. It will take a while.

From then, it will be a matter of modifying the method_ php to make predictions. Then it should be possible to get an accuracy estimate for carboxylic acids in OR51 receptors. Other ligands probably dock in a different part of the binding residues area; this may also be true of the tetrapod-like OR families.

All this calculation may ultimately require a rack mount server. They make ones now whose cooling fans don't sound like a jet engine. Tried looking into cloud computing, but anything in budget would be less powerful than the cheap used desktop I've been developing this project on.

2023-03-21 05:56 UTC, primaryodors requested changes

2023-03-21 05:56 UTC, primaryodors commented on primarydock.config
> +
May want to add something about axes based on a region, bw residue, or atom.

2023-03-21 05:56 UTC, primaryodors commented on src/classes/constants.h
> +#define allow_mol_fullrot_iter 1
Why is this enabled if axial tumble (line 157) is not?

2023-03-21 05:56 UTC, primaryodors commented on src/classes/protein.cpp
>  {
This looks like the same change as made in #213 - perhaps want to close the other PR?

2023-03-21 05:56 UTC, primaryodors commented on test/51e2_propionate.config
> +HXR 1 TMR6 6.26 6.60 6.48 0 0 0 0.5015 0 0.8651 3
These lines should all match, either all BW or all Cartesian axis.

2023-03-21 06:05 UTC, ssepeq commented on src/classes/constants.h
> +#define allow_mol_fullrot_iter 1
Will switch them in the morning and retest big three.

2023-03-21 14:51 UTC, ssepeq commented on src/classes/constants.h
> +#define allow_mol_fullrot_iter 1
The TAAR test result is not as good if axial tumble is enabled and not full rotations.

2023-03-22 05:10 UTC, ssepeq commented
🟩🟩🟩

2023-03-22 05:15 UTC, primaryodors approved these changes

2023-03-22 05:16 UTC, merged