#217 side chain flexion probabilities
primaryodors/primarydock pull request #219
Opened 2023-04-03 14:25 UTC by ssepeq

The new "flexion selection" feature correctly predicts that nonanoic acid is a non-agonist for OR51E2. The tail end of the ligand stays in the binding pocket, without moving Phe155, and the carboxylic acid makes contact with Arg262 almost right away in node 1 of the sweep, obviating receptor activation. (It's not known whether nonanoic acid is an antagonist, but this pattern of binding suggest antagonism would be likely.)

Running it on the server now to see what kind of accuracy it gets.

2023-04-03 14:36 UTC, ssepeq commented
🟥🟩...

TAAR test only took 235 seconds! Much faster now with fewer flexions. Incorrectly, it reports His107 as having a moderate repulsion with the ligand, when in fact there appear to be about 5A between them, besides the fact that this side chain would not be expected to have a negative charge in the configuration shown.

2023-04-04 13:07 UTC, ssepeq commented
The calculations on the server are producing some strange effects. Just checked the dock for propionic acid in 51E1 (should be an agonist) and there are no path nodes beyond node zero.

2023-04-08 02:58 UTC, primaryodors commented
The side chain flexions appear to be working as they should. Helix rotations are beyond the scope of this PR.

Should get this branch ready for merge (make sure it passes the TAAR and 1A1 tests) and then tackle the helix rotations in a new branch.

2023-04-08 03:10 UTC, ssepeq commented
🟥🟩🟥 

@%$#.

2023-04-08 03:31 UTC, ssepeq commented
🟥🟩🟩

2023-04-08 03:44 UTC, primaryodors requested changes

2023-04-08 03:44 UTC, primaryodors commented on predict/A51E2.pepd
> +# Pepteditor script for deriving active-state conformational changes from human β2 adrenergic receptor.
Description comment is wrong.

2023-04-08 03:44 UTC, primaryodors commented on predict/A51E2.pepd
> +# Origin will be the active m point.
These comments are also wrong.

2023-04-08 03:44 UTC, primaryodors commented on predict/A51E2.pepd
> +LET @point = @ic[%i] + @delta_n
Should this be @ delta_n or @ xform?

2023-04-08 03:44 UTC, primaryodors commented on predict/A51E2.pepd
> +# DUMP
This is no longer in use and should be removed.

2023-04-08 03:44 UTC, primaryodors commented on predict/analyze_emrot.php
> +
Remove extra blank lines from end of file.

2023-04-08 03:44 UTC, primaryodors commented on predict/method_emrots.php
> +// $outfname = str_replace(".dock", "_emrot.dock", $outfname);
Let's remove this comment and the comment block below.

2023-04-08 03:44 UTC, primaryodors commented on predict/methods_common.php
> +            // echo "$ln\n";
Let's remove this debug line.

2023-04-08 03:44 UTC, primaryodors commented on predict/methods_common.php
>              // echo "$ln\n";
And this one.

2023-04-08 03:44 UTC, primaryodors commented on src/classes/aminoacid.cpp
> -    //cout << aadef->_3let << residue_no << " vs " << other->aadef->_3let << other->residue_no;
Should remove this debug line and the one below it, or place them uncommented inside a compiler switch defined in constants.h.

2023-04-08 03:44 UTC, primaryodors commented on src/classes/atom.cpp
> +    if (atom->residue && btom->residue)
Should remove this debug trap.

2023-04-08 03:44 UTC, primaryodors commented on src/classes/molecule.cpp
> +            // cout << iter << ":" << mm[i]->name << " " << mm[i]->movability << endl;
Should either uncomment this or remove entirely.

2023-04-08 03:44 UTC, primaryodors commented on src/primarydock.cpp
> -        /*
Should remove this comment block.

2023-04-08 03:49 UTC, ssepeq commented on src/classes/aminoacid.cpp
> -    //cout << aadef->_3let << residue_no << " vs " << other->aadef->_3let << other->residue_no;
These were already removed. 😕

2023-04-08 03:51 UTC, ssepeq commented on src/primarydock.cpp
> -        /*
Consider it done. 👍🏼

2023-04-08 03:53 UTC, primaryodors approved these changes

2023-04-08 03:55 UTC, merged