Metal coordination in dock config file.
primaryodors/primarydock pull request #244
Opened 2023-05-06 17:04 UTC by ssepeq

A metal ion may now be specified in the config file to be added to the PDB before docking. It will act like an additional ligand, but with its coordinating residues frozen in place around it. The best-binding algorithm has been updated to treat a metal and its coordination residues as a single monolithic alignment target with a property of metallicity that favors sulfur atoms in ligands.

Also included are: increased flexibility of the ligand; reduced availability of backbone atoms for hydrogen bonding; an improvement to the viewer to avoid hiding side chains behind backbone cartoons.

2023-05-06 17:05 UTC, ssepeq commented
🟩🟩🟩

2023-05-06 18:13 UTC, primaryodors commented
Couple things with this PR...

The "sulfur kludge" is kind of antithetical to the design of PrimaryDock. Code shouldn't be tied to any specific element, just like we try not to tie code to specific amino acids (glycine being the exception since no other glycine-like α-amino acid is possible). Instead, we tie code to properties, such as the histidine flip which should work for any imidazole-containing AA etc. No element, other than perhaps hydrogen, is unique enough in all its properties to warrant coding for directly like this. How would a selenium-containing ligand behave in the real world under the conditions where this sulfur kludge would apply? It would be far better to specify "chalcogen within a specific electronegativity range" or even just "chalcogen" with electronegativity-specific feature multiplication factors rather than tying the code to a single element.

Similarly, commenting out the Cu...O coordination strength from bindings.dat is a poor way to deal with oxygen atoms coordinating with metal ions. Why wouldn't a ligand's hydroxy group coordinate to a Cu+ or a Cu2+? Could be the simulation is correct. If the journal article ran their simulation and found it does not coordinate, then there must be a documented reason why that can be used to inform PrimaryDock just as it was used to inform their docker. In that case, finding the answer and applying it to the code is more proper than willy nilly removing an interatomic binding potential simply because it was inconvenient.

Whatever reason would cause a hydroxy group to coordinate to other hydroxyls instead of to a metal, should also be the reason for not best-binding it to a metal "glom", cf. the sulfur kludge above.

As for the hydrogen bonding kludge, it can stay for now given the programming complexity involved in making H-bonding competitive. Going to start a new issue soon for adding that capability.

2023-05-06 18:22 UTC, primaryodors commented
This may be of help:

https://chem.libretexts.org/Courses/Saint_Marys_College_Notre_Dame_IN/CHEM_342%3A_Bio-inorganic_Chemistry/Readings/Metals_in_Biological_Systems_(Saint_Mary's_College)/Oxygen_transport_and_Storage/Blue_blood_(Invertebrates_molluscs_and_arthropods)/Haemocyanin

> Hard/Soft Acid/Base Theory (HSAB)
>
>Hard/Soft Acid/Base (HSAB) Theory allows for predictions of which acids and bases (metals and ligands) prefer to interact and which are most stable. In HSAB Theory, acids are electron acceptors and are referred to as acids/metal ions, and bases are electron donors and are referred to as ligands. These acids and bases can be categorized as hard or soft based on their charge density (charge to size ratio), polarizability (ability for an induced dipole to occur), and the covalent vs ionic nature of their interactions. Hard acids and bases have a higher charge density, are less polarizable, and/or have bonds that are more ionic; these tend to have a high charge and a small radius. On the other hand, soft acids and bases have a lower charge density, are more polarizable, and/or they have bonds that are more covalent; these tend to have a low charge and a large radius. HSAB can be used to predict which different metal-ligand pairs prefer to interact; hard acids prefer to coordinate with hard bases, soft acids prefer to coordinate with soft bases, and borderline acids prefer borderline bases. Essentially, the more “like” the characteristics of a metal and ligand, the stronger the preference of the ligand for that metal. This means that if there is a soft acid present,  Au+  for example, in the active site of a molecule, it will prefer to bind to a soft base, such as  S2− .10 In general, when you move down the periodic table, softness increases, and as you move right softness increases. Additionally, all of the bases are nonmetal electron donors (typically anions), and the acids are mostly metal ions.
>
> As seen in figure 2, the active site of hemocyanin contains two copper ions, each bound to three histidine (His) residues. When the Cu(I) ion binds to oxygen it is oxidized to Cu(II). Cu(I) is a soft acid, Cu(II) is a borderline acid, and the imidazole ring of histidine is a borderline base. Atoms or molecules that are classified as having intermediate characteristics are called borderline, as they do not lie at either extreme of the hard/soft spectrum; they are harder than metals that are categorized as “soft” and softer than metals categorized as “hard”. Nitrogens are typically classified as hard bases, however if a nitrogen is contained within an aromatic ring, the entire ring is more polarizable. For this reason, imidazole nitrogen atoms are classified as borderline bases. Because the copper ion alternates between a soft acid (Cu(I)) and a borderline acid (Cu(II)), it makes sense that it is bound to a borderline base. Borderline histidine is a better match for borderline Cu(II) than soft Cu(I), however His is still a better match for Cu(I) than a set of ligands that is harder. It is important to recognize, however, that there are other factors that affect metal ion selectivity, such as ionic size and ligand field stabilization energy, that must also be considered.

2023-05-06 18:58 UTC, ssepeq commented
https://doi.org/10.1002/anie.201007100

2023-05-06 19:39 UTC, ssepeq commented
This article in favor of HSAB gives numbers that would seem to predict that Cu2+ would preferentially coordinate to O rather than S: https://doi.org/10.1021%2Fja00364a005

2023-05-07 00:50 UTC, primaryodors commented
The question of HSAB vs. other methods warrants further study.

For this ticket, it is sufficient to code the following: Using the electronegativities of the ligand atom (El) and of the metal (Em), compute 0.5 + 0.5 * cos((El + Em) / 2 - 2.25) and use that as the multiplier for the ligand-metal coordination strength.

2023-05-07 04:47 UTC, ssepeq commented
The latest commit assumes that the metal ion is something with a higher electronegativity such as Cu. For olfaction, this might be a safe assumption, but for versatility, the best-binding algorithm should be rewritten to use potential binding energies between atoms instead of guessing with constant values for things like polarity, pi capability, charge, etc.

2023-05-07 04:57 UTC, primaryodors commented
Okay to go ahead with the potential binding energies method in this PR if it isn't too big a programming task.

2023-05-07 21:47 UTC, ssepeq commented
This is working currently:

```
PROT pdbs/OR2/OR2M3.upright.pdb
TEMPLATE pdbs/OR51/OR51E2.8f76.pdb
BRIDGE 6.57 45.51
LIG sdf/3-mercapto-2-methylpentan-1-ol.sdf

# https://doi.org/10.1007/s00018-019-03279-y
CEN RES 3.33 3.37 3.40 5.41 5.42 6.55
MCOORD Cu +1 5.42 5.43 5.46

SIZE 7.0 7.5 7.0
SOFT TMR2 TMR4 TMR5 TMR6 TMR7

EXCL 1 57		# Head, TMR1, and CYT1.
WET

POSE 10
ELIM 99
PROGRESS

FLEX 1
FLXR 3.33

ITERS 50

OUT output/%p_%l.active.dock
APPENDPROT
```

2023-05-09 06:03 UTC, ssepeq commented
This is the nonsense that it's pulling for glom pairing currently (using a thiolated ligand and after removing Met206(5.46) from metal coordination):

```
Final pair assignments:
atom_glom[ C1 C2 C3 C4 C5 C6 H9 H10 H11 H12 H13 H14 H15 H16 H17 H18 H19 H20 ]-residue_glom[ Cys202 Cys203 ]
atom_glom[ O7 H21 ]-residue_glom[ Cys202 Cys203 ]
atom_glom[ S8 ]-residue_glom[ Arg261 ]
```

2023-05-10 01:44 UTC, ssepeq commented
This PR is turning into another monster.

2023-05-10 04:27 UTC, ssepeq commented
TODO:

All the places where `multimol_conform()` is currently being called, should be replaced with calls to `conform_molecules()` instead. In cases where background molecules or molecules allowed to clash are specified, dedicated flags can be defined in `MovabilityType`.

Once all calls have been switched over, the monstrous `multimol_conform()` function and its myriad compiler constants can be removed.

All metal-binding code not pertaining to this PR should also be removed.

2023-05-12 11:14 UTC, ssepeq commented
Electronegativity changes with ionization charge. There's a formula in this paper: https://doi.org/10.1021/jp062886k that can be used to calculate an ion's electronegativity on the fly, so long as we add another dat file for information about ions, ionization energies, and crystalline ionic radii.

2023-05-12 14:53 UTC, primaryodors commented
Ion data would make a great topic for a future PR. Would like to get this PR wrapped up and ready to merge.

2023-05-15 18:16 UTC, ssepeq commented
🟩🟩🟩

2023-05-15 21:33 UTC, primaryodors requested changes
Let's also make sure the MCOORD command in Pepteditor works the same as the MCOORD parameter in PrimaryDock, i.e. they should both use the new metal coordination code.

Later, we'll be using a command line utility to identify and remove obsolete functions, and the above step will be helpful for that.

2023-05-15 21:33 UTC, primaryodors commented on primarydock.config
> +# on the command line, that argument will *not* override the SMILES string from the config
Let's fix it so if the user does specify a --lig on the command line, it clears out the SMILES string.

2023-05-15 21:33 UTC, primaryodors commented on src/classes/atom.cpp
> +        // Aromatic ring fix breaks molecule test.
Does the ring fix still break the two benzene molecules test?

2023-05-15 21:33 UTC, primaryodors commented on src/classes/intera.cpp
> +            /*if (forces[i]->type == vdW
Dead code that can be removed.

2023-05-15 21:33 UTC, primaryodors commented on src/classes/intera.cpp
> +                // Removing these two lines fixes anisotropy but breaks the molecule test.
Is this still happening?

2023-05-15 21:33 UTC, primaryodors commented on src/classes/molecule.cpp
> +        float ltheta = frand(-theta, theta); // theta*randsgn();
Dead code at end of line.

2023-05-15 21:33 UTC, primaryodors commented on src/primarydock.cpp
> +                                    // TODO: WTF was this for??????
Language.

2023-05-15 21:33 UTC, primaryodors commented on src/primarydock.cpp
> -                                    // if (sc_gloms[j].get_center().get_3d_distance(glomtmp.get_center()) < 0.01) too_similar = true;
Dead code.

2023-05-15 21:33 UTC, primaryodors commented on src/primarydock.cpp
>                                  // m.intermol_conform_norecen(alignment_aa[l], iters, reaches_spheroid[nodeno]);
Dead code.

2023-05-15 21:33 UTC, primaryodors commented on src/primarydock.cpp
>              /*time_t jlgsux = time(NULL);
Should remove this.

2023-05-15 21:33 UTC, primaryodors commented on src/primarydock.cpp
>              // cout << "Attempt " << drcount << " node " << nodeno << " pdbdat is " << dr[drcount][nodeno].pdbdat.length() << " chars." << endl;
Dead code.

2023-05-15 21:33 UTC, primaryodors commented on viewer.htm
>      // if (cen_ligand) curr_ligand.autoView();
Dead code.

2023-05-15 21:33 UTC, primaryodors commented on viewer.htm
>      // if (cen_ligand) curr_ligand.autoView();
Dead code.

2023-05-15 21:33 UTC, primaryodors commented on viewer.htm
>  	// cc.setSelection("*");
Dead code.

2023-05-15 21:33 UTC, primaryodors commented on viewer.htm
>  						stage.animationControls.rotate(quaternion);*/
Dead code.

2023-05-16 13:50 UTC, ssepeq commented
> Let's also make sure the MCOORD command in Pepteditor works the same as the MCOORD parameter in PrimaryDock, i.e. they should both use the new metal coordination code.
> 
> Later, we'll be using a command line utility to identify and remove obsolete functions, and the above step will be helpful for that.

They're different formats with different capabilities. The amount of development involved would deserve its own PR. Recommend adding an obsolescence notice to the Pepteditor MCOORD and ultimately replacing it with some kind of all-purpose atom/molecule coordination/prosthetic group feature, i.e. something that could add not only metal ions but also retinal, heme, etc.

2023-05-16 14:51 UTC, primaryodors commented
The deprecated notice will be fine.

2023-05-16 22:39 UTC, primaryodors requested changes
Just a few more items.

2023-05-16 22:39 UTC, primaryodors commented on src/aniso_test.cpp
> +        //if (ifs[x]->get_type() == hbond)
Dead code.

2023-05-16 22:39 UTC, primaryodors commented on src/aniso_test.cpp
> +            // break;
Dead code.

2023-05-16 22:39 UTC, primaryodors commented on src/aniso_test.cpp
> +                // cout << tb;
Dead code.

2023-05-16 22:39 UTC, primaryodors commented on src/aniso_test.cpp
> +                /*if (!x && !y)
What was the reason for commenting this block?

2023-05-16 22:39 UTC, primaryodors commented on src/primarydock.cpp
> +            // mcoord_resno[j++] = atoi(words[i]);
Dead code.

2023-05-16 22:39 UTC, primaryodors commented on src/primarydock.cpp
> +        // mcoord_resno[j] = 0;
Dead code.

2023-05-17 00:44 UTC, ssepeq commented on src/aniso_test.cpp
> +                /*if (!x && !y)
Because that code was causing this garbage to happen:

![image](https://github.com/primaryodors/primarydock/assets/66374250/41e44386-0249-4672-9ad7-4bfe1fceb46e)

2023-05-17 00:55 UTC, primaryodors commented on src/aniso_test.cpp
> +                /*if (!x && !y)
Do you see why it's doing that?

2023-05-17 01:01 UTC, ssepeq commented on src/aniso_test.cpp
> +                /*if (!x && !y)
Yes, and I fixed an unrelated geometry bug.

2023-05-17 02:23 UTC, primaryodors approved these changes

2023-05-17 02:23 UTC, primaryodors commented
🟩🟩🟩

2023-05-17 02:24 UTC, merged

2023-05-17 03:59 UTC, ssepeq commented
Drat. The side chain flexion stuff from #217 seems to have come undone with this PR. Even metal coordinating residues are flexing willy nilly.

2023-05-17 04:07 UTC, primaryodors commented
This is the kind of thing that should be tested before marking the PR ready for review!