G-protein based reshaping
primaryodors/primarydock pull request #268
Opened 2023-06-04 12:06 UTC by ssepeq

This PR contains a facility for coupling two proteins, altering the shape of one to conform to the other.

2023-06-10 15:55 UTC, ssepeq commented
> There is a hydrophobic pocket in the cryo-EM model formed by I125, I220, V224, L227 of OR51E2 and L388, L393, L394 of GNAS. As these are not direct contacts between individual aminos but rather a general grouping, there ought to be a way to define such a thing as another form of contact point.

_Originally posted by @ssepeq in https://github.com/primaryodors/primarydock/issues/260#issuecomment-1585667301_

I125 is part of the MAYDRYVAIC motif. Trying using these as ordinary contacts for now.

2023-06-10 23:28 UTC, primaryodors commented
So this is working now? Ready to run the Big Three tests and then merge?

Then onward to unit tests?

2023-06-10 23:41 UTC, ssepeq commented
I want to at least get this cronned on the local server. Have to test ORs that have an EXR salt bridge, and write a cronnable PHP script.

2023-06-10 23:56 UTC, primaryodors commented
There's already a PHP script at `predict/generate_couple.php`, isn't it already set up on the server cron?

2023-06-10 23:57 UTC, ssepeq commented
And it's failing on OR1A1 + hGNAL.

```
couple: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```

2023-06-11 01:03 UTC, ssepeq commented
This is not working. This is not even close to working. OR1A1 is failing horribly with both GNAS and GNAL.

2023-06-11 01:07 UTC, primaryodors commented
Time to put this aside and work on the unit tests.

2023-06-11 01:18 UTC, ssepeq commented
😭

2023-06-11 01:37 UTC, ssepeq commented
About to start running the cron on the server. OR1A1 is fixed. Switching gears to the unit tests.

2023-06-14 04:35 UTC, ssepeq commented
Though the cron has just begun, it has so far identified a handful of OR1A1 agonists that bind better to the G-protein-coupled PDBs than to the inactive PDB. One example:

```
        "geraniol":
        {
            "inactive": 13.386333333333333,
            "version": 1686708796,
            "Actual": "Agonist",
            "hGNAL": -2.7592,
            "hGNAS2": -8.30297
        },
```

Letting it run for several days to collect more data for predictions. As yet, no non-agonists have been processed. Importantly, not all agonists are giving negative energies in the coupled PDBs, though all but one (dihydrojasmone) give better energies for at least one of the coupled PDBs compared to the inactive model. The ability to expand into other G-proteins will be important, and more work is necessary for the docking itself, which is currently using tumble spheres instead of best-binding.

2023-06-14 04:51 UTC, primaryodors commented
Remember that the goal is not simply to identify agonists, but to reliably distinguish agonists from non-agonists.

Since the protein coupling was the original point of this PR, and that seems to be working well, let's go ahead and test the big three tests and if that looks good then this can be merged. The precise details of protein coupling can be addressed in future issues and PRs. It's fine to include the new prediction method, since having any up to date method is better than not having one, however further development on predictions should also happen in future PRs.

2023-06-14 13:17 UTC, ssepeq commented
The aminos calculate differently on the local machine vs. the server, so it was important to check in the amino acid SDFs and round the similarities in the grid to the nearest 0.02.

🟩...

2023-06-14 13:58 UTC, ssepeq commented
🟩🟩🟥

2023-06-14 14:19 UTC, ssepeq commented
Molecular "ESP" stopped working with the new conform_molecules() function. Restoring that might fix the OR1A1 test.

2023-06-14 14:44 UTC, primaryodors commented
Not thrilled to hear that functionality was lost in the rewrite of the multi-molecule function, but let's put the "ESP" feature on hold for now. After finishing this PR, we can rename that feature to "lookahead" and implement it in a new branch.

The big three tests were working before the code changes in this PR. It would be best to start by going backwards through the git log until the test begins working again, in order to narrow down which code change caused it to fail. Then that change should be manually removed from the latest commit.

2023-06-15 00:39 UTC, ssepeq commented
🟩🟩🟩

2023-06-16 19:31 UTC, primaryodors requested changes

2023-06-16 19:31 UTC, primaryodors commented on data/gprots_aligned.txt
> +                                                                            IEKXLXXEKE
What is this line for?

2023-06-16 19:31 UTC, primaryodors commented on predict/generate_couple.php
> +# TEMPLATE pdbs/OR51/OR51E2.8f76.pdb
Let's uncomment this template line.

2023-06-16 19:31 UTC, primaryodors commented on predict/methods_common.php
> +                    if (isset($metrics_to_process["$mode.rgn"]))
Should document all the possible array keys for `$metrics_to_process`.

2023-06-16 19:31 UTC, primaryodors commented on test/test_51e2.cplcfg
Is this file being used?

2023-06-19 23:28 UTC, ssepeq commented
It is giving results no better than chance. I'm turning off the cron.

```
Results for OR1A1:
56 correct predictions (37.33%).
  65 false positives.
  29 false negatives.

Results for OR1A2:
9 correct predictions (47.37%).
  5 false positives.
  5 false negatives.

Results for OR1B1:
2 correct predictions (100%).
  0 false positives.
  0 false negatives.

Results for OR1C1:
3 correct predictions (7.32%).
  24 false positives.
  14 false negatives.

Results for OR1D2:
9 correct predictions (21.95%).
  0 false positives.
  32 false negatives.

Total:
79 correct predictions (31.23%).
  94 false positives.
  80 false negatives.
```

2023-06-19 23:38 UTC, ssepeq commented on data/gprots_aligned.txt
> +                                                                            IEKXLXXEKE
Neglected to remove it.

2023-06-20 02:14 UTC, ssepeq commented
Uncommenting the template line is causing the TMR5 and TMR6 regions to pivot too much, breaking contact with the hydrophobic pocket and resulting in clashes with side chain atoms of TMR3.

2023-06-21 14:59 UTC, ssepeq commented
Prolines confuse the new connection code. Also, residues are getting strewn somehow.

2023-06-22 13:33 UTC, ssepeq commented
🟩🟩🟩

2023-06-22 14:45 UTC, ssepeq commented
Getting some really nice docks spot checking receptors with known agonists.

[OR1D2_hGNAL_bourgeonal.dock.txt](https://github.com/primaryodors/primarydock/files/11835220/OR1D2_hGNAL_bourgeonal.dock.txt)
[OR1D2_hGNAL_floralozone.dock.txt](https://github.com/primaryodors/primarydock/files/11835221/OR1D2_hGNAL_floralozone.dock.txt)
[OR2T34_hGNAL_floralozone.dock.txt](https://github.com/primaryodors/primarydock/files/11835223/OR2T34_hGNAL_floralozone.dock.txt)
[OR2AG1_hGNAS2_isoamyl acetate.dock.txt](https://github.com/primaryodors/primarydock/files/11835226/OR2AG1_hGNAS2_isoamyl.acetate.dock.txt)

2023-06-22 14:59 UTC, primaryodors commented on PREDICTION.md
> +`$bias_by_energy`       TODO: This has not been implemented yet.
This will be important to squeeze in.

2023-06-22 15:13 UTC, primaryodors commented on PREDICTION.md
> +`ACVTH.TMR1` thru `ACVTH.TMR7`
Can this be made compatible with the `.rgn` syntax?

2023-06-22 15:33 UTC, primaryodors approved these changes

2023-06-22 15:39 UTC, merged