Coupled Homology
primaryodors/primarydock pull request #290
Opened 2023-07-04 17:47 UTC by ssepeq

This is mutually exclusive with #286 and #289 as there would be many conflicts due to copied code.

Trying something different. If we can do homologous conformational changes to ORs based on the OR51E2 cryo-EM, then why not for the mTAAR9 cryo-EMs and various other experimental models of coupled GPCRs. The placement of the G protein can be part of the homology model.

2023-07-05 02:35 UTC, ssepeq commented
The IDs of the removed PDBs are:

2ydo
3rfm
5g53
2rh1
4ldo
P38405

2023-07-05 06:06 UTC, ssepeq commented
It is downloading the PDBs, opening the receptors and alpha subunits, uprighting the assemblies, and outputing them beautifully to example coupled PDBs.

Next step will be to examine the mTAAR9-hGNAS2 examples having different ligands, and see how much they vary in order to estimate whether "soft" docks will be necessary. Soft docking is far more CPU intensive than normal docking. A small variance between models may mean that soft docking would not be important, but ORs have "softer" binding pockets than TAARs.

Then there will have to be some kind of layer between the coupled PDBs and the PrimaryDock app, or else a new feature internal to the app, to do the conformational change of the OR in parallel to the coupled PDB and its inactive counterpart. This functionality will first apply the changes to activate the inactive OR for a given G protein, then fine-tune the receptor's shape to optimize G protein contact, optimize internal contacts such as Y6.55-D/E45.51, and minimize clashes. Finally, the custom tuned receptor will be ready for dock.

2023-07-05 18:53 UTC, primaryodors commented
The results are looking great!

Recall that we want to create coupled versions of the odor receptor PDBs and store them in the `pdbs/coupled/` folder, then do docking against those. The idea is for the coupled models to be reusable for all ligands. Therefore, they wouldn't be generated on the fly by a function of `bin/primarydock`.

2023-07-07 02:52 UTC, ssepeq commented
This is almost ready, just have to figure out how best to fit in reshaping the receptors to minimize internal clashes and clashes with the G protein.

It's making promising looking predictions so far. I'm thinking of readying this for merge and starting on a UI feature that would display predictions on the odorant page in the web app.

2023-07-07 06:15 UTC, primaryodors commented
Minimizing clashes is more important than the UI, and the receptor conformations should be fixed in this PR.

The UI feature can wait until the server has processed at least a few hundred receptor-odorant pairs.

2023-07-10 07:19 UTC, primaryodors commented
This PR has gotten way too big. Let's make sure it passes the unit test and then ready it for merge. @ssepeq

2023-07-10 14:59 UTC, primaryodors commented
Once the clash avoidance is working, go ahead and test and mark the PR ready for review. The contact residues can be addressed in a new ticket.

2023-07-11 00:21 UTC, ssepeq commented
Created #292.

Hoping ticket 292 fixes problems with residue 292 of OR51E2 reaching the ligand. 🤡

2023-07-11 03:21 UTC, ssepeq commented
Test succeeded.

2023-07-11 17:30 UTC, primaryodors requested changes

2023-07-11 17:30 UTC, primaryodors commented on src/interpreter.cpp
> +                        ref = new Protein("reference");
Same thing here, another opportunity to improve the code to prevent a memory leak. Protein objects are fairly sizable, so it's not an insignificant leak.

2023-07-11 17:30 UTC, primaryodors commented on src/interpreter.cpp
> +				// strcpy(buffer, "$PDB");
Dead code.

2023-07-11 17:30 UTC, primaryodors commented on src/interpreter.cpp
> +                // strcpy(buffer, "$PROTEIN");
Dead code.

2023-07-11 17:30 UTC, primaryodors commented on src/interpreter.cpp
> +                // strcpy(buffer, "%SEQLEN");
Dead code.

2023-07-11 17:30 UTC, primaryodors commented on src/interpreter.cpp
> +                // strcpy(buffer, "$SEQUENCE");
Dead code.

2023-07-11 17:30 UTC, primaryodors commented on src/interpreter.cpp
> +                // if (working == strands[chain]) raise_error("Cannot delete current working strand.");
Dead code.

2023-07-11 17:30 UTC, primaryodors commented on SCRIPTING.md
> +Deletes the indicated strand (peptide chain). Note the current working strand cannot be deleted; an error will result.
Isn't this no longer true about deleting the working strand?

Also, do we have a unit test for what happens when a script deletes the working strand?

2023-07-11 17:30 UTC, primaryodors commented on test/motif_test.pepd
> +IF %motif > 0 THEN ECHO "Found KLFNKRISS motif at " %motif
This should just say terminal motif or XXXX$ motif, rather than assuming the sequence.

2023-07-11 17:30 UTC, primaryodors commented on test/point_test.approved.txt
> +Point pt6 from SCoord v is 3.52537e-07 Angstroms from pt5.
Can this be rounded down to zero, or else just indicated that it's less than some threshold value?

2023-07-11 17:30 UTC, primaryodors commented on SCRIPTING.md
> +Substrings can be accessed via dot notation, e.g. `$string.10` or `$string.10,3` or `$string.%start,%len`.
Should clarify here that the second separator is always a comma.

2023-07-11 17:33 UTC, primaryodors commented
Not wanting to wait for the requested changes on this ticket, the 3 letter fix has been added to `stable` so that the current stable branch is no longer broken.

2023-07-11 17:35 UTC, primaryodors requested changes

2023-07-11 17:35 UTC, primaryodors commented on test/unit_test_master.sh
> +                printf "${RED}TAAR test FAILED: bad PDB data.${NC}\n"
Let's also add the 3 letter test to the d-limonene test dock.

2023-07-12 05:12 UTC, ssepeq commented on SCRIPTING.md
> +Deletes the indicated strand (peptide chain). Note the current working strand cannot be deleted; an error will result.
Any such unit test would fail because #282 is still utterly hosed.

2023-07-12 14:07 UTC, ssepeq commented on src/classes/protein.cpp
> +            int sftop = residues[j]->get_residue_no();
It's resno, but with all the letters incremented.

2023-07-12 14:21 UTC, ssepeq commented on src/interpreter.cpp
> +                esr = er; // - strlen(psz);
Allows the search to proceed all the way to the end of the search region instead of stopping n chars short, where n is the length of the search motif. This is necessary for searching e.g. XXXXX$ where the old code would have stopped 6 chars short of the end, failing to even look at the C-terminus residue.

2023-07-12 23:49 UTC, primaryodors commented on src/classes/protein.cpp
> +            int sftop = residues[j]->get_residue_no();
Let's change it to resno2 or something similarly readable.

2023-07-12 23:52 UTC, primaryodors commented on SCRIPTING.md
> +Deletes the indicated strand (peptide chain). Note the current working strand cannot be deleted; an error will result.
Do you have the changes from the following commit in your branch? 

https://github.com/primaryodors/primarydock/commit/1185db877899f084342dbdfc66f9ea315904a51d

2023-07-13 00:16 UTC, ssepeq commented on test/mol_assem_test.toluene.approved.txt
> +Atom C1 has bond angles: 180 70.5 70.5 109.5 109.5 109.5
Yup, it's pretty badly broken.

![image](https://github.com/primaryodors/primarydock/assets/66374250/d2417014-c085-4f08-89f2-dcf1dfac2eaf)

2023-07-13 00:21 UTC, ssepeq commented on SCRIPTING.md
> +Deletes the indicated strand (peptide chain). Note the current working strand cannot be deleted; an error will result.
I don't. Merging it now...

2023-07-13 00:26 UTC, ssepeq commented on SCRIPTING.md
> +Deletes the indicated strand (peptide chain). Note the current working strand cannot be deleted; an error will result.
Now the anisotropy test is failing, smh.

2023-07-13 00:32 UTC, primaryodors commented on SCRIPTING.md
> +Deletes the indicated strand (peptide chain). Note the current working strand cannot be deleted; an error will result.
This means 3 things are broken now that were working before, none of which are related to the topic of this PR. Something is very very wrong.

2023-07-13 00:33 UTC, primaryodors commented
PR rejected.

2023-07-13 00:33 UTC, closed without merging

2023-07-13 00:38 UTC, ssepeq commented
TWO WEEKS OF PROGRESS JUST GONE???????????

2023-07-13 00:44 UTC, primaryodors commented
Take some time away from the project.