Ssepeq pose class
primaryodors/primarydock pull request #96
Opened 2022-07-26 14:32 UTC by ssepeq

2022-07-26 14:32 UTC, ssepeq commented
The local server keeps intermittently segfaulting.

2022-07-28 01:46 UTC, ssepeq commented
cis-3-hexen-1-ol is now intermittently failing in OR1A1.

2022-07-29 13:50 UTC, ssepeq commented
Lyral and linalool have been failing in OR1A1. Lyral is not an agonist and is physically too big to fit in the binding pocket. Linalool is a weak agonist.

Saito et al (https://doi.org/10.1126/scisignal.2000016) report that lyral is a non-agonist, but Adipietro et al (https://doi.org/10.1371/journal.pgen.1002821) report it as an inverse agonist. Looking at the structure of lyral, both the 3D structure on pubchem and the structure generated by obabel have the aldehyde group pointing in the polar direction off the cyclohexene ring. Since PrimaryDock cannot yet bend that ring, it cannot move that ring member such that the aldehyde falls equatorially; if it could, the dock might succeed. 

Alternatively, there's no enantiomer selection in the SMILES string for lyral, and commercial samples of the odorant are probably typically racemic, it being a synthetic compound. (One manufacturer calls it a "mixture of isomers".) So it may be that one enantiomer is an inverse agonist while the other does not fit into the pocket. The 3D structure on Good Scents (http://www.thegoodscentscompany.com/opl/31906-04-4.html) has the aldehyde group positioned equatorially.

2022-07-30 15:44 UTC, ssepeq commented
Linalool still fails in OR1A1. It's worse at 50 iterations than at 100. 200 iterations takes way too long.

2022-07-30 16:35 UTC, ssepeq commented
200 iterations takes half an hour to generate one pose. Inexcusable.

2022-07-31 14:45 UTC, ssepeq commented
Waiting to see how many dismal failures this foolish thing generates on the local server before green lighting this for review and merge.

2022-07-31 14:50 UTC, ssepeq commented on src/primarydock.cpp
> +    	ligand->crumple(fiftyseventh*44);
Dratbil.

2022-08-01 23:17 UTC, primaryodors approved these changes

2022-08-01 23:18 UTC, primaryodors requested changes
Unacceptable.

2022-08-01 23:18 UTC, closed without merging